# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29d07a7ffd4d31aa8d78a88e1ad0a37cd959cb155e7289b4a3f7485175fac8cbbf51a3f00e779312c994ea89e5d3f1ae58acc758b5ccbbcc1b31a4754ffb1c0b

test:
  secret_key_base: 734ebf50df7ca41a17e96cd44f20e1a387ac8e934a5be26e840c8b82ef25ca8b74ea030db2d0568e3f54b436005b475bee836bea00a18df2e08f0f69ead89357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
